FROM mubox/arch-env

ARG INSTALLER_VERSION
ARG MICROBOX_VERSION
ARG VIRTUALBOX_VERSION
ARG VIRTUALBOX_REVISION
ARG DOCKER_MACHINE_VERSION

# Make directory for files to live in
RUN mkdir -p /fakeroot/amd64/usr/local/bin

# fetch microbox
RUN curl -fsSL -o /fakeroot/amd64/usr/local/bin/microbox "https://s3.amazonaws.com/tools.microbox.cloud/microbox/v$MICROBOX_VERSION/linux/amd64/microbox"
RUN chmod +x /fakeroot/amd64/usr/local/bin/microbox

# fetch microbox-update
RUN curl -fsSL -o /fakeroot/amd64/usr/local/bin/microbox-update "https://s3.amazonaws.com/tools.microbox.cloud/microbox/v$MICROBOX_VERSION/linux/amd64/microbox-update"
RUN chmod +x /fakeroot/amd64/usr/local/bin/microbox-update

# fetch openvpn
RUN curl -fsSL -o /fakeroot/amd64/usr/local/bin/microbox-vpn "https://s3.amazonaws.com/tools.microbox.cloud/openvpn/linux/amd64/openvpn"
RUN chmod +x /fakeroot/amd64/usr/local/bin/microbox-vpn

# fetch docker-machine
RUN curl -fsSL -o /fakeroot/amd64/usr/local/bin/microbox-machine "https://github.com/docker/machine/releases/download/v$DOCKER_MACHINE_VERSION/docker-machine-Linux-x86_64"
RUN chmod +x /fakeroot/amd64/usr/local/bin/microbox-machine

# Create Package
COPY descfile /

RUN fpm -t pacman -a amd64 -n microbox --description "$(cat /descfile)" -v $INSTALLER_VERSION -s dir /fakeroot/amd64/usr/local/bin/=/usr/bin/
