#!/bin/sh

INSTALLER_VERSION=$1
MICROBOX_VERSION=$2
VIRTUALBOX_VERSION=$3
VIRTUALBOX_REVISION=$4
DOCKER_MACHINE_VERSION=$5

set -e

docker build --no-cache -t windows-installer \
  --build-arg INSTALLER_VERSION=$INSTALLER_VERSION \
  --build-arg MICROBOX_VERSION=$MICROBOX_VERSION \
  --build-arg VIRTUALBOX_VERSION=$VIRTUALBOX_VERSION \
  --build-arg VIRTUALBOX_REVISION=$VIRTUALBOX_REVISION \
  --build-arg DOCKER_MACHINE_VERSION=$DOCKER_MACHINE_VERSION \
  -f Dockerfile.windows .
CONTAINER="$(docker run -d windows-installer)"
mkdir -p dist/windows
docker cp "${CONTAINER}":/installer/Output/MicroboxSetup.exe dist/windows/
# docker cp "${CONTAINER}":/installer/Output/MicroboxSetup-signed.exe dist/
docker rm "${CONTAINER}" 2>/dev/null || true
