#!/bin/bash

INSTALLER_VERSION=${1}
MICROBOX_VERSION=${2}
VIRTUALBOX_VERSION=${3}
VIRTUALBOX_REVISION=${4}
DOCKER_MACHINE_VERSION=${5}

set -e

docker build --no-cache -t debian-installer \
  --build-arg INSTALLER_VERSION=${INSTALLER_VERSION} \
  --build-arg MICROBOX_VERSION=${MICROBOX_VERSION} \
  --build-arg VIRTUALBOX_VERSION=${VIRTUALBOX_VERSION} \
  --build-arg VIRTUALBOX_REVISION=${VIRTUALBOX_REVISION} \
  --build-arg DOCKER_MACHINE_VERSION=${DOCKER_MACHINE_VERSION} \
  -f Dockerfile.debian .
CONTAINER="$(docker run -d debian-installer)"
mkdir -p dist/linux
docker cp "${CONTAINER}":/microbox_${INSTALLER_VERSION}_amd64.deb dist/linux/
docker cp "${CONTAINER}":/microbox_${INSTALLER_VERSION}_arm64.deb dist/linux/
docker cp "${CONTAINER}":/microbox_${INSTALLER_VERSION}_armhf.deb dist/linux/
docker cp "${CONTAINER}":/microbox_${INSTALLER_VERSION}_s390x.deb dist/linux/
docker rm "${CONTAINER}" 2>/dev/null || true
