#!/bin/bash

INSTALLER_VERSION=${1}
MICROBOX_VERSION=${2}
VIRTUALBOX_VERSION=${3}
VIRTUALBOX_REVISION=${4}
DOCKER_MACHINE_VERSION=${5}

set -e

docker build --no-cache -t arch-installer \
  --build-arg INSTALLER_VERSION=${INSTALLER_VERSION} \
  --build-arg MICROBOX_VERSION=${MICROBOX_VERSION} \
  --build-arg VIRTUALBOX_VERSION=${VIRTUALBOX_VERSION} \
  --build-arg VIRTUALBOX_REVISION=${VIRTUALBOX_REVISION} \
  --build-arg DOCKER_MACHINE_VERSION=${DOCKER_MACHINE_VERSION} \
  -f Dockerfile.arch .
CONTAINER="$(docker run -d arch-installer /bin/bash)"
mkdir -p dist/linux
docker cp "${CONTAINER}":/microbox-${INSTALLER_VERSION}-1-x86_64.pkg.tar.zst dist/linux/
docker rm "${CONTAINER}" 2>/dev/null || true
